"""Production settings.

Hard requirements (process refuses to boot otherwise):

- ``DJANGO_SECRET_KEY``    — >= 50 chars, generated by a CSPRNG, stored in a
  secret manager and rotated on a schedule.
- ``DJANGO_ALLOWED_HOSTS`` — explicit host list / wildcard subdomain.
- ``POSTGRES_PASSWORD``    — database credential.

Verify with ``python manage.py check --deploy`` on every release; the CI
pipeline must treat any warning as a build failure.
"""
from __future__ import annotations

from django.core.exceptions import ImproperlyConfigured

from .base import *  # noqa: F403
from .base import env_bool, env_int, env_list, env_str

# --- Core hardening ---------------------------------------------------------

DEBUG = False  # Never overridable by environment in production.

SECRET_KEY = env_str("DJANGO_SECRET_KEY")
if len(SECRET_KEY) < 50 or SECRET_KEY.startswith("django-insecure-"):
    raise ImproperlyConfigured(
        "DJANGO_SECRET_KEY must be a unique, randomly generated value of at "
        "least 50 characters. Generate one with "
        "django.core.management.utils.get_random_secret_key()."
    )

ALLOWED_HOSTS = env_list("DJANGO_ALLOWED_HOSTS")
if not ALLOWED_HOSTS:
    raise ImproperlyConfigured("DJANGO_ALLOWED_HOSTS must be set in production.")

CSRF_TRUSTED_ORIGINS = env_list("DJANGO_CSRF_TRUSTED_ORIGINS", "https://*.meridian.app")

# --- Transport security ------------------------------------------------------

SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

SECURE_HSTS_SECONDS = env_int("DJANGO_SECURE_HSTS_SECONDS", 31_536_000)  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Only honour X-Forwarded-Proto when Django is strictly behind a TLS-
# terminating proxy that overwrites the header on every request. If this is
# set while directly internet-facing, clients could spoof "https" and bypass
# SECURE_SSL_REDIRECT.
if env_bool("DJANGO_BEHIND_TLS_PROXY", True):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# --- Browser-side protections -------------------------------------------------

SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"
SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin"
X_FRAME_OPTIONS = "DENY"

# --- Database ----------------------------------------------------------------

# TLS to PostgreSQL is mandatory in production.
DATABASES["default"]["OPTIONS"]["sslmode"] = env_str("DB_SSLMODE", "require")  # noqa: F405
if DATABASES["default"]["OPTIONS"]["sslmode"] in {"disable", "allow"}:  # noqa: F405
    raise ImproperlyConfigured("DB_SSLMODE must be 'require' or stronger in production.")
